swagger: '2.0'
info:
  title: "SafeSpace Risk Assessment App"
  description: "API to manage the Risk Assessment App for SafeSpace Financial"
  version: "1.0.0"
host: "local"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"

securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header

paths:
 # Accounts
 # Users

